# .github/workflows/test.yml
name: Run Tests and Linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test on multiple Python versions you support
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install the package with test dependencies
        # Ensure you have defined the [test] extra in setup.cfg
        pip install .[test]

    # Optional: Add linting/formatting checks (requires ruff in [dev] extra)
    # - name: Install dev dependencies
    #   run: pip install .[dev]
    # - name: Lint with Ruff
    #   run: ruff check .
    # - name: Check formatting with Ruff
    #   run: ruff format --check .

    - name: Run tests with pytest
      run: |
        # Assuming your tests are in a 'tests/' directory
        # Create this directory and add tests!
        # pytest tests/
        echo "No tests found. Please create tests in the 'tests/' directory."
        # Exit gracefully for now if no tests dir exists
        if [ ! -d "tests" ]; then exit 0; else pytest tests/; fi
